# Generated by Django 5.2.1 on 2025-06-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialno', models.CharField(max_length=100, unique=True)),
                ('itemname', models.CharField(max_length=100)),
                ('itemdomain', models.CharField(max_length=100)),
                ('itemqty', models.IntegerField()),
                ('itemimg', models.ImageField(blank=True, null=True, upload_to='items/')),
            ],
        ),
    ]
