# Generated by Django 5.2.1 on 2025-06-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Super User', 'Super User'), ('Lead', 'Lead'), ('Product Manager', 'Product Manager'), ('Domain Head', 'Domain Head'), ('Department Resource Head', 'Department Resource Head'), ('Student', 'Student')], default='SU', max_length=50),
        ),
    ]
