# Generated by Django 5.2.1 on 2025-06-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_rename_items_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_userid', models.CharField(max_length=50)),
                ('borrower_name', models.CharField(max_length=100)),
                ('borrower_roll', models.CharField(max_length=50)),
                ('borrow_serialno', models.CharField(max_length=50)),
                ('borrow_itemname', models.CharField(max_length=100)),
                ('borrow_itemdomain', models.CharField(max_length=50)),
                ('borrowermobile', models.CharField(max_length=15)),
                ('borrowreason', models.TextField()),
                ('borrowqty', models.PositiveIntegerField()),
                ('borrow_returndate', models.DateField()),
                ('borrow_status', models.CharField(default='Pending', max_length=20)),
                ('is_pm_approved', models.BooleanField(default=False)),
                ('is_dh_approved', models.BooleanField(default=False)),
                ('is_drh_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
