# Generated by Django 5.2.1 on 2025-06-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('Super User', 'Super User'), ('Lead', 'Lead'), ('Product Manager', 'Product Manager'), ('Domain Head', 'Domain Head'), ('Department Resource Head', 'Department Resource Head'), ('Student', 'Student')], max_length=50, null=True),
        ),
    ]
