# Generated by Django 5.2.1 on 2025-06-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='is_Lead_approved',
            field=models.BooleanField(default=False),
        ),
    ]
