# Generated by Django 5.2.1 on 2025-06-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_borrowrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='borrow_made_date_time',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='rejection_reason',
            field=models.CharField(default='', max_length=50),
        ),
    ]
