# Generated by Django 5.2.1 on 2025-06-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0004_borrowrequest_is_lead_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('Super User', 'Super User'), ('Lead', 'Lead'), ('Product Manager', 'Product Manager'), ('Domain Head', 'Domain Head'), ('Domain Resource Head', 'Domain Resource Head'), ('Student', 'Student')], max_length=50, null=True),
        ),
    ]
