# Generated by Django 5.2.1 on 2025-06-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0005_alter_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowrequest',
            name='final_approved',
        ),
        migrations.RemoveField(
            model_name='borrowrequest',
            name='is_returned',
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='borrow_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Returned', 'Returned')], default='Pending', max_length=20),
        ),
    ]
