# Generated by Django 5.2.1 on 2025-06-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0006_remove_borrowrequest_final_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
    ]
