# Generated by Django 5.2.1 on 2025-06-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0007_borrowrequest_is_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrequest',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
