# Generated by Django 5.2.1 on 2025-06-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0008_alter_borrowrequest_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='rejectedby',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
