# Generated by Django 5.2.1 on 2025-06-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0009_borrowrequest_rejectedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='is_damaged',
            field=models.BooleanField(default=False),
        ),
    ]
