# Generated by Django 5.2.1 on 2025-06-30 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0010_borrowrequest_is_damaged'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentroll', models.CharField(blank=True, max_length=50, null=True)),
                ('block_reason', models.CharField(blank=True, max_length=50, null=True)),
                ('blocked_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
