# Generated by Django 5.2.1 on 2025-06-30 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0011_blacklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='block_reason',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='blocked_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='rejectedby',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
