# Generated by Django 5.2.1 on 2025-07-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0012_alter_blacklist_block_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='damage_descp',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
